// <auto-generated />
namespace services.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class renamedetaillocationcreelsurvey : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(renamedetaillocationcreelsurvey));
        
        string IMigrationMetadata.Id
        {
            get { return "201409301901306_rename-detail-location-creelsurvey"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
